#!/bin/sh
#
# Git pre-commit hook script to run Django tests before committing.
#
# This script navigates to the `backend` directory and runs the tests
# using the command `poetry run python manage.py test`. If the tests fail,
# the commit is aborted.

# Redirect output to stderr.
exec 1>&2

# Navigate to the `backend` directory
echo "Navigating to the 'backend' directory..."
cd backend || {
    echo "Error: Unable to find or navigate to the 'backend' directory. Aborting commit."
    exit 1
}

echo "[+] Running Formatter..."
poetry run black .

echo "[+] Running Linter..."
poetry run ruff check --fix

# Run tests using `poetry`
echo "[+] Running Django tests..."
poetry run python manage.py test

# Return to the repository root after tests pass
cd - >/dev/null || exit

echo " ======= All tests passed. Proceeding with commit. ======="

