name: Commit Stage

on:
  push:
    branches: [ main, dev]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name:  Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    - name: Install dependencies
      working-directory: ./backend
      run: poetry install --no-interaction --no-root

    - name: Check formatting
      working-directory: ./backend
      run: poetry run black .

    - name: Run Ruff as a linter
      working-directory: ./backend
      run: poetry run ruff check --fix

    - name: Analyse Python code for security issues
      working-directory: ./backend
      run: poetry run bandit -ll -r ./backend

    - name: Test with pytest
      working-directory: ./backend
      run: poetry run python manage.py test
